### ISSUE TITLE
Allow disabling rolling-updates when applying

### ISSUE THREAD

**Issue by ari-becker** [eddycharly/terraform-provider-kops#14]
We intentionally don't run `kops rolling-update cluster` every time / in an automated way when we update our cluster, since we also run databases (Kafka...) in our Kubernetes cluster, and trying to rotate the cluster without paying attention to the database internals would result in data loss.

I propose adding a `apply_rolling_update_cluster : true / false` variable (even if it's `true` by default) which would simply skip applying the rolling-update phase at the end.

**Comment by eddycharly** [comment]
Hey @ari-becker !

Thanks for raising the issue, i had the same discussion with my team mates yesterday.
It could be added easily but i feel like it's opening doors to uncontrolled drift. I mean using terraform is to make sure the infrastructure does not diverge from the source of truth and this would allow such a divergence by design.

I would be happy to discuss this more though and i'm not against adding it as long as it's an opt-in user choice.

**Comment by ari-becker** [comment]
@eddycharly Right, I would completely understand having `apply_rolling_update_cluster` default to `true`, as described. Teams that don't need the drift shouldn't needlessly suffer from it :)

Because of these requirements though, we ended up building our own rolling-update mechanism that relies on Prometheus metrics to know when it's safe to continue the rollout. It's a little heavy-handed, but it's the price we pay to run 100% Kubernetes. It's also one of the reasons why we run Kops and not one of the managed Kubernetes providers (e.g. EKS), because they would try to just treat the database-hosting nodes like any other worker nodes and accidentally cause data loss on our end. I do think that having this kind of flexibility is one of the reasons why people pick Kops instead of a managed provider.

**Comment by eddycharly** [comment]
@ari-becker I see your point, i'm going to add support for optional rolling update and validation.

**Comment by eddycharly** [comment]
I opened a PR.

It will look like
```hcl
rolling_update_options {
  skip = true
}
```

Same thing for validating the cluster.

**Comment by ari-becker** [comment]
Fantastic, thank you!

**Comment by eddycharly** [comment]
I moved the options in the provider config rather than in the cluster resource itself.
