### ISSUE TITLE
Add support to re-use existing aws provider

### ISSUE THREAD

**Issue by wesselvdv** [eddycharly/terraform-provider-kops#228]
Is it possible to add support to re-use an existing aws provider configuration? Much like you can pass around a specific provider to modules or resources?

Related to #229, as the required options in that issue are coming from the existing aws provider configuration.

**Comment by eddycharly** [comment]
Using an existing provider is going to be hard, kOps does everything by itself.
I’ll add the missing options.

**Comment by wesselvdv** [comment]
I have no idea how that works under the hood, but I gather it's not that possible to reference to different configuration properties from passed in provider?

**Comment by eddycharly** [comment]
I definitely don't see how to do this honestly.

**Comment by eddycharly** [comment]
@wesselvdv can I close this one ? I don’t see it happen tbh.

**Comment by wesselvdv** [comment]
Yes, lets close. It was just an idea.
