### ISSUE TITLE
Add support for more aws configuration options other than profile, assume_role and region.

### ISSUE THREAD

**Issue by wesselvdv** [eddycharly/terraform-provider-kops#229]
I am using a S3 compatible bucket that requires some serious additional configuration options to be configured to allow it to work:

```terraform
provider "kops" {
  state_store = "s3://${data.pass_password.kops_s3_bucket.password}"

  aws {
    secret_key = data.pass_password.kops_s3_secret_access_key.password
    access_key = data.pass_password.kops_s3_access_key_id.password
    region = data.pass_password.kops_s3_region.password

    endpoints {
      s3 = data.pass_password.kops_s3_endpoint.password
    }

    skip_requesting_account_id = true
    skip_credentials_validation = true
  }
}
```

Without these additional configuration options I am unable to provide kOps access to the S3 state store.

**Comment by eddycharly** [comment]
Sure, I’ll add those shortly, thanks for asking.

**Comment by wesselvdv** [comment]
I am using the 1.20-alpha btw, not sure if that makes a difference.

**Comment by eddycharly** [comment]
I don’t think I’ll back port it to previous versions (unless someone asks for it) so it’s fine :)

**Comment by eddycharly** [comment]
Not sure if i can add everything you need 🤔 

```
    skip_requesting_account_id = true
    skip_credentials_validation = true
```

I'm not sure how i can make kOps understand this.

Did you look at this https://github.com/kubernetes/kops/blob/master/docs/state.md ?
Are you using an S3 compatible endpoint ?

**Comment by wesselvdv** [comment]
You’re right, I guess that everything that kOps understands is good enough. That works for us using the kOps CLI

**Comment by eddycharly** [comment]
I added a few options here https://github.com/eddycharly/terraform-provider-kops/commit/01e1fe7b76ea3774340286504922aca80ba78e84
Do you think it could suit your needs ?

**Comment by wesselvdv** [comment]
Oh hell yes, that’s sweet! Thanks for spending the time to get this kind of stuff in!

**Comment by eddycharly** [comment]
`v1.20.0-alpha.2` should be available in a couple minutes (https://github.com/eddycharly/terraform-provider-kops/actions/runs/926316835)

If you need some specific openstack settings (swift ?) i can add this too.

**Comment by wesselvdv** [comment]
I don’t need any of that, but I do think it’s useful to have it in anyway. I’d be easier for other who do use Swift in combination with Openstack.

**Comment by eddycharly** [comment]
Ok, I’ll wait someone asks for it then.

**Comment by wesselvdv** [comment]
I do need other openstack options though, I have no use for swift but anything openstack related I definitely need!

**Comment by eddycharly** [comment]
Let me know what is missing and I’ll add it.
It should not be long to add.

**Comment by wesselvdv** [comment]
I am not sure if the openstack credentials are picked up from the env by kOps with this provider? Or should they be passed in as with AWS? I am running into some errors which could be because it's unable to auth to openstack. If they're being picked up just like the openstack provider, then I might not need anything else. Still investigating where this new error is coming from..

**Comment by eddycharly** [comment]
I guess I should add support for the variables here https://github.com/kubernetes/kops/blob/97869057129b30ea284c3ed1bdf1db36e752701d/util/pkg/env/standard.go#L50

I’ll do that tomorrow.

**Comment by eddycharly** [comment]
For sure the env variables won’t be picked up automatically.
The provider is running in its own process and I don’t think it will inherit the env vars at all.

**Comment by eddycharly** [comment]
@wesselvdv I added openstack options here https://github.com/eddycharly/terraform-provider-kops/commit/cf13c768b8e93e74c06e1743f56a69e376afc86e

`v1.20.0-alpha.3` is being built.

**Comment by wesselvdv** [comment]
Awesome! I've tried it, and it seems to be working. I am running into other issues, that I am investigating now. Will come back here if I am missing a variable.

**Comment by wesselvdv** [comment]
Is there a way to pass in the debug env variables to kops? I am getting an error on allocating a floating ip that's failing due to the resource missing, but I can't really debug it without more information. It might be because we're using a self signed certificate on the openstack side that i've previously passed in using the env variable `OS_CACERT`, but that's hard to discern if I can't increase the amount of debugging.

**Comment by eddycharly** [comment]
I think it’s not possible as is but I’ll look into it. Shouldn’t be difficult at all.

Did you try to increase the terraform log level ?
kOps code should log errors if any.

**Comment by eddycharly** [comment]
Hmmm, that's not so easy, there is no kOps env variable, it's `klog` doing some trickery with the command line directly.
I need to find a way to set `klog` log level programatically.

**Comment by wesselvdv** [comment]
I'll close this issue as this has been resolved, and I'll open a new one to investigate how to support the cli equivalent of `-v <debuglevel>`.
