### ISSUE TITLE
Whats the easiest way to import an existing Kops cluster on AWS?

### ISSUE THREAD

**Issue by theFong** [eddycharly/terraform-provider-kops#231]
Love this project!

Is there documentation about what the subnets name, provider_id, type, and zone and where I can find those values if I already created the cluster's networking with Kops?

Thanks!

**Comment by eddycharly** [comment]
Hello,
You can import your cluster with `terraform import` command, the network infos should be imported in your state.
After that you can adapt you tf code to match what was imported ?

**Comment by eddycharly** [comment]
See https://github.com/eddycharly/terraform-provider-kops#importing-an-existing-cluster

**Comment by theFong** [comment]
Great! I think the command I was looking for was `terraform state show kops_cluster.cluster`.

Im now getting the error `The argument "network_id" is required, but no definition was found.` and `The argument "provider_id" is required, but no definition was found.` Are these the vpc id and subnet id respectively?

**Comment by eddycharly** [comment]
`network_id` is the vpc id.
`provider_id` is the subnet id.

I'm not quite sure how kOps works when it creates the network.

I guess it creates the vpc/subnets then adds them in the cluster spec 🤔 

Are those values set when you look at the cluster spec yaml object stored in the s3 bucket ?

**Comment by theFong** [comment]
It doesn't look like the vpc id and subnet id are in the cluster spec unfortunately

**Comment by eddycharly** [comment]
Ok so kops has to deduce this every time it runs ?
I’ll check the code but it’s really the case you have no other choice than identify the vpc id and subnet ids to fill the gap.
