### ISSUE TITLE
Add Support for kOps Secrets

### ISSUE THREAD

**Issue by theFong** [eddycharly/terraform-provider-kops#232]
Would be great to support creation of [kOps Secrets](https://kops.sigs.k8s.io/cli/kops_create_secret/). I use them to provide docker hub api credentials via the [dockerconfig secret](https://kops.sigs.k8s.io/cli/kops_create_secret_dockerconfig/).

**Comment by eddycharly** [comment]
Thanks for opening the issue, I’ll look into it ASAP.

**Comment by eddycharly** [comment]
@theFong I implemented basic support for `kops_dockerconfig`.

This is completely untested for now and very subject to change but if you try it out i would be interested to know how things go.

In the end, i feel like it would make sense to embed it in the cluster resource as there can be only one dockerconfig per cluster.
I will probably take some time later this week to implement it this way as i plan to cut a beta release for 1.20 this week and would like to include this in the beta.

The doc (very simple) is here https://github.com/eddycharly/terraform-provider-kops/blob/main/docs/resources/docker_config.md and `v1.20.0-alpha.4` should be available.

**Comment by eddycharly** [comment]
@theFong I'm changing the implementation in #266 
I will test it this week and plan to release a beta for 1.20.

**Comment by eddycharly** [comment]
Closing, it's included in `v1.20.0-beta.1` that was just released.
