### ISSUE TITLE
Add support for Node Problem Detector addon

### ISSUE THREAD

**Issue by theFong** [eddycharly/terraform-provider-kops#250]
https://kops.sigs.k8s.io/addons/#node-problem-detector

**Comment by eddycharly** [comment]
Hello @theFong NPD is introduced in kOps 1.22, it will be supported when 1.22 is released.

**Comment by eddycharly** [comment]
Closing, it will be released when kOps 1.22 is released.
Please reopen at this time if something is wrong.
