### ISSUE TITLE
Add equivalent of `-v` flag of cli to increase debug level information

### ISSUE THREAD

**Issue by wesselvdv** [eddycharly/terraform-provider-kops#252]
Add equivalent of `-v` flag of cli to increase debug level information. kOps is using `klog`, and it's unclear how to set this level programmatically.

**Comment by wesselvdv** [comment]
I see you've added preliminary support for this in b668a96cc231c4f6a724a46b2702897fb2919a9f, mind to release it so I can use it for #251 ?

**Comment by eddycharly** [comment]
Yeah, sure.
Beware that it's completely untested though, let me know if it works and helps.

`v1.20.0-alpha.5` is being released and should be available in a couple of minutes.

**Comment by eddycharly** [comment]
It should be fixed, please reopen if the issue persists.

**Comment by wesselvdv** [comment]
The latest version doesn't have the verbosity block.

**Comment by eddycharly** [comment]
Hello, look at the example [here](https://github.com/eddycharly/terraform-provider-kops/blob/01bdcf6317aa32eff568f8ec0b8de45cbb1a7fd9/examples/klog/provider.tf#L10-L18), it should be present.

Or maybe i didn't release this change yet ? 🤔
