### ISSUE TITLE
kubelet anonymousAuth not being passed to kubelet

### ISSUE THREAD

**Issue by rmgpinto** [eddycharly/terraform-provider-kops#256]
kubelet and kube-api-server are not receiving the `anonymous_auth` parameter from terraform.

config:

```
kubelet {
  anonymous_auth = false
}
kube_api_server {
  anonymous_auth = false
}

```

kubelet cmdline on node
```
/usr/local/bin/kubelet --authentication-token-webhook=true
--authorization-mode=Webhook--cgroup-driver=systemd
--cgroup-root=/
--client-ca-file=/srv/kubernetes/ca.crt
--cloud-provider=aws
--cluster-dns=10.0.0.10
--cluster-domain=cluster.local
--enable-debugging-handlers=true
--evictionhard=memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
--hostname-override=ip-10-0-157-188.eu-west-1.compute.internal
--kubeconfig=/var/lib/kubelet/kubeconfig
--max-pods=17
--network-plugin=cni
--non-masquerade-cidr=10.0.0.0/16
--pod-manifest-path=/etc/kubernetes/manifests
--register-schedulable=true
--register-with-taints=node-role.kubernetes.io/master=:NoSchedule
--resolv-conf=/run/systemd/resolve/resolv.conf
--v=2
--volume-plugin-dir=/usr/libexec/kubernetes/kubelet-plugins/volume/exec/
--cloud-config=/etc/kubernetes/cloud.config
--node-ip=10.0.157.188
--container-runtime=remote
--runtime-request-timeout=15m
--container-runtime-endpoint=unix:///run/containerd/containerd.sock
--tls-cert-file=/srv/kubernetes/kubelet-server.crt
--tls-private-key-file=/srv/kubernetes/kubelet-server.key
```

There should be an `--anonymous-auth=false`

Can you check this please? Thanks

edit: just check now, and if I pass `yes` then the flag `--anonymous-auth=true` is added to kubelet and to kube-api-server. Maybe something wrong with the code processing the false values?

**Comment by eddycharly** [comment]
Hello @rmgpinto 👋 
Thanks for reporting. I'll look at it but i'm pretty sure i'm not catching the difference between null and false.
It's a common problem when translation from hcl config to go struct.

**Comment by eddycharly** [comment]
See the expansion code here https://github.com/eddycharly/terraform-provider-kops/blob/9fa064e31447923e7b9cf421805e34b543c6cb7b/pkg/schemas/kops/Resource_KubeletConfigSpec.generated.go#L115-L117.
One hack to fix this to make the parameter mandatory but it's not silver bullet as null gets unsupported.

**Comment by eddycharly** [comment]
I think a solution would be to make the argument a struct, something like this:
```hcl
  kubelet{
    anonymous_auth {
      value = true
    }
  }
```

**Comment by rmgpinto** [comment]
If it fixes the problem, that would be great!

**Comment by eddycharly** [comment]
There are two possible solutions, the one above or:

```hcl
  kubelet{
    anonymous_auth = false
    anonymous_auth_specified = true
  }
```

I'm not a big fan of adding a `_specified` argument for every prop that is a pointer in kOps.

**Comment by rmgpinto** [comment]
Not a big fan either, and it would cause confusion.

**Comment by eddycharly** [comment]
I agree, I'm making this change, i had this in mind for some time.

**Comment by rmgpinto** [comment]
Thank you very much!

**Comment by eddycharly** [comment]
WIP here https://github.com/eddycharly/terraform-provider-kops/pull/258
It's gonna be a huge change though.

**Comment by rmgpinto** [comment]
> I think a solution would be to make the argument a struct, something like this:
> 
> ```terraform
>   kubelet{
>     anonymous_auth {
>       value = true
>     }
>   }
> ```

Hi, just my two cents regarding the PR and the code above.

I thought only kubelet -> anonymous_auth was going to be this way, but I saw the PR and every value will change. IMO this is not a very terraform way of specifying values.

I'd simplify things and set a sensible default for `anonymous_auth` and other boolean values, if the value is not specified.

**Comment by eddycharly** [comment]
> I thought only kubelet -> anonymous_auth was going to be this way, but I saw the PR and every value will change.

The issue happens with every prop that is a pointer in kOps code, not only kubelet `anonymous_auth` unfortunately.

For some props, setting a sensible default value will do the trick but in some cases where `null`, `false` and `true` can have a different meaning.

Going through all props and finding a sensible value is gonna be a pain and I feel like a lot of bugs are introduced because of this.

> IMO this is not a very terraform way of specifying values, and it's a significant drift from standards.

I agree but i find the syntax not that hard to understand and it would fix the issue once for all (leaving complete freedom to the end user).

This is a bit of a pain that terraform has no solution for this (see https://github.com/hashicorp/terraform-plugin-sdk/issues/261).

What do you think ? What are the drawbacks you see in applying it to all pointer props ?

**Comment by rmgpinto** [comment]
does this: https://stackoverflow.com/questions/43351216/check-if-boolean-value-is-set-in-go help?

I understand the issue with `nil` vs `false` but on the PR there are changes like:

```
member {
      name = "master-0"
      instance_group {
        value = "master-0"
      }
    }
```

Which are odd to me... Why do string values need to be changed as well?
Trying to push for a better solution here :)

**Comment by eddycharly** [comment]
I wonder why it is a pointer in kOps in the first place (https://github.com/kubernetes/kops/blob/559b57ea4c85931987da2bb1de85f7d9cd81f880/pkg/apis/kops/cluster.go#L586)

TBH it's probably safe to interpret `""` as `null` here but in some cases interpreting zero as `null` is not correct (see https://github.com/kubernetes/kops/blob/559b57ea4c85931987da2bb1de85f7d9cd81f880/pkg/apis/kops/instancegroup.go#L224 for example), in this case if we interpret 0 as `null` it will be equivalent to 100% instead of 0% :(

**Comment by eddycharly** [comment]
But i agree it could be nuanced for some props.

**Comment by eddycharly** [comment]
@rmgpinto second try https://github.com/eddycharly/terraform-provider-kops/pull/259

Maybe safer 🤷

**Comment by rmgpinto** [comment]
Amazing @eddycharly, looking forward for a new release!

**Comment by eddycharly** [comment]
Ok, let's merge the pr and see how things go 🤞

**Comment by eddycharly** [comment]
`v1.20.0-alpha.6` is being built.

Thanks for your great feedback, let me know if it fixes your issue.

**Comment by rmgpinto** [comment]
Thanks! I'll test today or the latest tomorrow.

**Comment by rmgpinto** [comment]
Just tested this, looks good to me. Thanks for the quick response.
