### ISSUE TITLE
kops_cluster_updater verbosity

### ISSUE THREAD

**Issue by rmgpinto** [eddycharly/terraform-provider-kops#261]
Me again :)

It would be very useful to have `kops_cluster_updater` be as verbose as a `kops rolling-update cluster --yes`
I just have a bunch of lines like:

```
kops_cluster_updater.updater: Still creating...
kops_cluster_updater.updater: Still creating...
kops_cluster_updater.updater: Still creating...
...
```

**Comment by eddycharly** [comment]
Definitely but I don’t know any way of doing this with terraform, I’m not sure at all it’s even possible  :(

You can use the tf env variables to get more logs though (TF_LOG, TF_LOG_PATH etc…)

**Comment by eddycharly** [comment]
I feel like it's the way terraform works unfortunately :(
Can we close the issue or is there something i can do for this ?

**Comment by rmgpinto** [comment]
Go ahead and close, thanks.

**Comment by eddycharly** [comment]
I'll look into it but chances that something exists are pretty low, i've never seen a provider sending messages to the end user.
