### ISSUE TITLE
Node termination handler enableSQSTerminationDraining support

### ISSUE THREAD

**Issue by theFong** [eddycharly/terraform-provider-kops#262]
It doesn't seem like there is [sqs termination support](https://kops.sigs.k8s.io/addons/#node-termination-handler) in the config. Is this the case?

**Comment by eddycharly** [comment]
It comes with kOps 1.21 (https://kops.sigs.k8s.io/addons/#queue-processor-mode). 

It is not yet supported (1.20 is in alpha, I will add 1.21 support soon).

**Comment by theFong** [comment]
Ah I didn't see that it was 1.21 👍

**Comment by eddycharly** [comment]
I started to implement 1.21 support in #271 

It should take a couple of days though.
