### ISSUE TITLE
Provider for arm64 architecture

### ISSUE THREAD

**Issue by rmgpinto** [eddycharly/terraform-provider-kops#349]
To use this provider with the Apple M1 laptop, it needs to be compiled and published with the arm64 arch.
Thanks

**Comment by eddycharly** [comment]
Maybe it can be added here https://github.com/eddycharly/terraform-provider-kops/blob/c8e951205888bf7b9ec216e692bdf44c86a40a73/.goreleaser.yaml#L18-L19

**Comment by rmgpinto** [comment]
is it `arm64` then?

**Comment by eddycharly** [comment]
> is it arm64 then?

I guess yes, but never tried this out. Wanna open a PR ?

**Comment by eddycharly** [comment]
Let's see if it works https://github.com/eddycharly/terraform-provider-kops/actions/runs/1233294974 🤞

**Comment by eddycharly** [comment]
@rmgpinto the build succeeded, can you check it out please ?

**Comment by rmgpinto** [comment]
Seems to be working now, thank you.

**Comment by eddycharly** [comment]
Nice, i'll close the issue then. Thanks for your pr !
