### ISSUE TITLE
feat: support custom CA

### ISSUE THREAD

**Issue by peter-svensson** [eddycharly/terraform-provider-kops#361]
Any plans on supporting [this](https://kops.sigs.k8s.io/custom_ca/)

Passing a custom CA would make it easier to spin up clusters using the same CA (and thus not needing to have a new kuber config except for the api url).

**Comment by eddycharly** [comment]
I’ll look at it, I already implemented some secrets so it should be pretty easy.

**Comment by eddycharly** [comment]
It should look something like this https://github.com/eddycharly/terraform-provider-kops/pull/362

**Comment by peter-svensson** [comment]
Tested the branch and it seems to work just fine!

**Comment by eddycharly** [comment]
Thanks for trying it out.
