### ISSUE TITLE
Make StateStore an attribute of cluster/ig resources

### ISSUE THREAD

**Issue by fcrespofastly** [eddycharly/terraform-provider-kops#379]
Hey there! 

Thanks for building this, it's awesome! 

We have a use case where we want to create the S3 bucket with terraform, since the kops provider uses the provider object to se the bucket, there's no way to interpolate the created bucket with terraform and therefore we have to hardcode it. 

Do you think it's feasible to move the state store configuration to the resource/datasource level?

Thanks!

**Comment by fcrespofastly** [comment]
Maybe an alternative approach could be letting the resource/datasource object override the provider config?

**Comment by eddycharly** [comment]
Closing for now, i don't think it will be addressed soon, sorry.
