### ISSUE TITLE
Webhook auth mode support

### ISSUE THREAD

**Issue by theFong** [eddycharly/terraform-provider-kops#382]
Do you know if its possible to override [these values](https://pkg.go.dev/k8s.io/kops/pkg/apis/kops?utm_source=godoc#KubeAPIServerConfig) with the provider?

I am trying to enable[ Webhook auth mode](https://kubernetes.io/docs/reference/access-authn-authz/webhook/).

**Comment by eddycharly** [comment]
Yes, you can configure this using `kube_api_server_config`, see https://registry.terraform.io/providers/eddycharly/kops/latest/docs/resources/cluster#kube_api_server_config
Is this what you're after ?

**Comment by eddycharly** [comment]
Closing, looks like it's already implemented, please reopen if needed.
