### ISSUE TITLE
1.21.3 always wants to remove secrets for ca cert

### ISSUE THREAD

**Issue by argoyle** [eddycharly/terraform-provider-kops#437]
Since upgrading to 1.21.3, terraform apply always wants to remove secrets for ca cert:
```
      ~ secrets {
          - cluster_ca_cert = (sensitive value)
          - cluster_ca_key  = (sensitive value)
            # (1 unchanged attribute hidden)
        }
```

It doesn't cause any harm to the cluster but there is always an update to apply.

**Comment by eddycharly** [comment]
Thanks for reporting. I’ll look into it asap.

**Comment by argoyle** [comment]
Just for extra info, I have not passed any specific CA cert into my cluster so those are the generated ones.

**Comment by eddycharly** [comment]
Did you provide a docker config secret ?

**Comment by argoyle** [comment]
Yes I did.

**Comment by eddycharly** [comment]
I think the fix is here https://github.com/eddycharly/terraform-provider-kops/pull/439 🤞

**Comment by eddycharly** [comment]
@argoyle can we close the issue now #439 was merged and released ?

**Comment by argoyle** [comment]
Yes, works fine! Closing.
