### ISSUE TITLE
Possibility to create cluster without Admin SSH Key

### ISSUE THREAD

**Issue by peter-svensson** [eddycharly/terraform-provider-kops#446]
Since it is possible to create a kops [cluster](https://kops.sigs.k8s.io/cli/kops_create_cluster/) without specifying an admin ssh key it would be nice to be able to do that using the provider as well.

Connecting to the instances is still possible with for example [ec2-instance-connect](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-methods.html#connect-options)

**Comment by eddycharly** [comment]
Thanks for raising the issue, i'll look at it tonight or tomorrow.

**Comment by eddycharly** [comment]
#447 should fix the issue 🤞 

Beware it's only available since kOps 1.22, but I didn't release the provider based on kOps 1.22 yet though. 
There is an alpha version for it but couldn't find the time to try it out.

**Comment by eddycharly** [comment]
I released `v1.22.0-alpha.3` if you want to try the changes in #447

**Comment by eddycharly** [comment]
@peter-svensson can we close the issue as it should have been fixed in #447 ?
We can reopen it or create another one if there is a bug in the implementation.

**Comment by peter-svensson** [comment]
Yes - close it 😊
