### ISSUE TITLE
Network requisites for installation

### ISSUE THREAD

**Issue by shmul** [eddycharly/terraform-provider-kops#471]
Hi,

Thanks for the effort you put into this project. I tried two examples, the basic and the bastion and both failed to complete successfully, presumably because the network and security (for bastion) pre-requisites weren't fully done. I noticed that the load balancer wasn't able to reach the instances (they are all marked as inactive).
Can you please provide the configuration details for the subnets and internet gateway (is it needed)? Also, what is needed for the bastion security groups?

Cheers,
Shmul

**Comment by eddycharly** [comment]
Network has to be created beforehand. It all depends on how you created your network (subnets, vpn, etc…), there’s not a single solution.

kOps docs should help, typically the docs for running a cluster in an existing network.

Internet access is required for kOps to create a cluster. It can be used in an air gapped environment but it’s a complex setup, not sure if it’s what you’re looking for.

What network topology did you try ?

**Comment by eddycharly** [comment]
I'll close this issue for now, please reopen if necessary.
