### ISSUE TITLE
Setting a value for Duration attributes in cluster resource generates diff in every plan

### ISSUE THREAD

**Issue by wandera-petr-cerny** [eddycharly/terraform-provider-kops#495]
Hi! I would appreciate a guidance on working with Duration attributes of `kops_cluster` resource. 
As an example, using the following code
```
resource "kops_cluster" "this" {
  ...
  kubelet {
    cpu_cfs_quota_period               = "5ms"
    image_pull_progress_deadline = "1m0s"
  ...
```
generates following plan
```
      ~ kubelet {
          ~ cpu_cfs_quota_period                = "&Duration{Duration:5ms,}" -> "5ms"
          ~ image_pull_progress_deadline        = "&Duration{Duration:1m0s,}" -> "1m0s"
```
which is applied with every run successfully, but it is quite annoying (and it triggers cluster rolling update).

Passing `"&Duration{Duration:5ms,}"` as a value to `cpu_cfs_quota_period` attribute does not show any changes in `terraform plan`, but when building cluster from scratch, any value passed in such notation leads to effectively having value `0s`. This is quite bad, because trying to set `attach_detach_reconcile_sync_period` attribute in `kube_controller_manager` block and building a cluster from scratch leads to cluster never starting as the Kube Controller Manager never starts due to the reconcile period being effectively set to 0.

It seems to me that either I don’t understand how to pass values to Duration attributes, or the issue caused by using version `1.21.4` of the provider and `0.13.4` of Terraform, or there might be some bug? We do plan to upgrade to newer versions of both kops and Terraform, but we have couple of blockers that currently prevent us from using kops 1.22+.

Any help or guidance would be highly appreciated!

**Comment by eddycharly** [comment]
Thanks for reporting, it looks like a bug !
I will look at it tomorrow.

**Comment by wandera-petr-cerny** [comment]
Hi @eddycharly, thanks for your response! Did you have any luck looking into this? Can I provide any more details to help you with the investigation by any chance?

**Comment by eddycharly** [comment]
Hi @wandera-petr-cerny I'm going to release 1.22 today :crossed_fingers: 
There was a bunch of changes in regards to the code generation in this release. Could you give it a try ?
For the record, using the 1.22 version doesn't mean you need to upgrade k8s to 1.22.

**Comment by eddycharly** [comment]
I'll close this issue for now, please reopen if necessary.
