### ISSUE TITLE
kops_kube_config data source documentation is outdated

### ISSUE THREAD

**Issue by aberenshtein** [eddycharly/terraform-provider-kops#500]
In the Example usage
data "kops_kube_config" "kube_config" {
  cluster_name = "cluster.example.com"
}

# then you can configure another provider based on the kube_config data source

provider "kubectl" {
  host                   = data.kops_kube_config.kube_config.server
  username               = data.kops_kube_config.kube_config.kube_user
  password               = data.kops_kube_config.kube_config.kube_password
  client_certificate     = data.kops_kube_config.kube_config.client_cert
  client_key             = data.kops_kube_config.kube_config.client_key
  cluster_ca_certificate = data.kops_kube_config.kube_config.ca_cert
}

  cluster_ca_certificate = data.kops_kube_config.kube_config.ca_cert should be
  cluster_ca_certificate = data.kops_kube_config.kube_config.ca_certs

**Comment by eddycharly** [comment]
Thanks for reporting. Fixing it now.
