### ISSUE TITLE
Propagate kOps logs

### ISSUE THREAD

**Issue by ddelange** [eddycharly/terraform-provider-kops#529]
Hi 👋 

even when I run `TF_LOG=DEBUG terraform apply`, there is basically no output on what's going on under the hood:

```
kops_cluster_updater.updater: Still modifying... [id=my-cluster.example.com, 1m30s elapsed]
kops_cluster_updater.updater: Still modifying... [id=my-cluster.example.com, 1m40s elapsed]
kops_cluster_updater.updater: Still modifying... [id=my-cluster.example.com, 1m50s elapsed]
...
```

Could the logs coming from kOps/tf be propagated to the main thread somehow?

**Comment by eddycharly** [comment]
This is a limitation of terraform unfortunately :(
You can log into a file though. See https://www.jorgebernhardt.com/terraform-troubleshooting-logging/ for example.
