### ISSUE TITLE
cannot find CA certificate when using data.kops_kube_config

### ISSUE THREAD

**Issue by clayrisser** [eddycharly/terraform-provider-kops#557]
I get the following error when using `data.kops_kube_config`

```
data.kops_kube_config.this: Reading...
│ Error: cannot find CA certificate
│ 
│   with data.kops_kube_config.this,
│   on data.tf line 38, in data "kops_kube_config" "this":
│   38: data "kops_kube_config" "this" {
```

Here is the config I'm using.

```tf
provider "kops" {
  state_store = "s3://${var.bucket}/kops"
  aws {
    region = var.region
  }
}

resource "kops_cluster" "this" {
...
}

data "kops_kube_config" "this" {
  cluster_name = kops_cluster.this.id
}

provider "helm" {
  kubernetes {
    client_certificate     = data.kops_kube_config.this.client_cert
    client_key             = data.kops_kube_config.this.client_key
    cluster_ca_certificate = data.kops_kube_config.this.ca_cert
    host                   = data.kops_kube_config.this.server
    password               = data.kops_kube_config.this.kube_password
    username               = data.kops_kube_config.this.kube_user
  }
}
```

**Comment by eddycharly** [comment]
Thanks for reporting, could it be related to https://github.com/eddycharly/terraform-provider-kops/issues/438 ?
IIRC this is not a lazy operation, therefore the cluster has to be up and running to fetch the kubeconfig and initialize the helm provider.

**Comment by clayrisser** [comment]
Is there not a way to watch for the cluster to be alive and healthy?

**Comment by clayrisser** [comment]
I would use the following script to ensure my cluster and nodes were healthy when I used eks.

```tf
resource "null_resource" "wait_for_nodes" {
  provisioner "local-exec" {
    command     = <<EOF
while [ "$(kubectl --kubeconfig <(echo $KUBECONFIG) get nodes | \
  tail -n +2 | \
  grep -vE '^[^ ]+\s+Ready')" != "" ]; do
    sleep 10
done
EOF
    interpreter = ["sh", "-c"]
    environment = {
      KUBECONFIG = local.kubeconfig
    }
  }
  depends_on = [
    kops_cluster.this
  ]
}
```

**Comment by eddycharly** [comment]
I don't think so.
The `helm` provider is initialized before the cluster is created but depends on a `data` that itself depends on the cluster...
I don't understand why such things are allowed in terraform TBH.

**Comment by clayrisser** [comment]
Would there be a way to create the certs and credentials first, use them for the kubeconfig, and then inject them into kops?

**Comment by clayrisser** [comment]
Also, I'm going to try the solution you referenced earlier. Hopefully that does the trick for me. Still a little ugly and not the terraform way.

https://github.com/eddycharly/terraform-provider-kops/issues/438#issuecomment-998591993

**Comment by eddycharly** [comment]
I would recommend separating states. On state for the cluster, and another one for helm charts ?

**Comment by clayrisser** [comment]
Fair enough. So I guess I have enough to go off of to get around this issue.

However, now when I try and deploy the cluster I get the following error. Any direction on what's causing this?

```
╷
│ Error: cannot determine hash for "https://storage.googleapis.com/kubernetes-release/release/v1.22/bin/linux/amd64/kubelet" (have you specified a valid file location?)
│ 
│   with kops_cluster_updater.updater,
│   on cluster.tf line 146, in resource "kops_cluster_updater" "updater":
│  146: resource "kops_cluster_updater" "updater" {
│ 
╵
```

**Comment by eddycharly** [comment]
No idea, can you share your tf config ?

**Comment by eddycharly** [comment]
Closing as this does not seem related to this provider, please reopen if needed.
