### ISSUE TITLE
kops_cluster_updater thinks there's a revision when there are no changes

### ISSUE THREAD

**Issue by clayrisser** [eddycharly/terraform-provider-kops#569]
kops_cluster_updater thinks there's a revision when there are no changes. This creates a big problem when I make changes to my terraform config that do not affect kops, because the cluster still thinks it needs to update when it does not need to update.

I believe this is caused because the kops_cluster and the kops_instance_group revision increments every time, even when there are no changes.

This ends up causing all of the nodes to get destroyed and recreated every time I run terraform apply, and it can take over 30 minutes when this happens.

How can I avoid the kops cluster from upgrading when I haven't made changes to it?

How can I prevent all the nodes from being destroyed and recreated when I make changes that should cause the nodes to be destroyed, for example simply trying to scale the nodes groups?

**Comment by clayrisser** [comment]
I think it's related to issue #530 because I'm using secrets.

**Comment by eddycharly** [comment]
Hi, this sounds very strange, the revision should increase only when something change in the cluster or instance group.
I don't understand why your nodes are destroyed/recreated, this should not happen.
Can you share your updater config ?

**Comment by eddycharly** [comment]
Closing, I think it has been fixed, please reopen if needed.
