### ISSUE TITLE
Provider want to remove instance group labels

### ISSUE THREAD

**Issue by argoyle** [eddycharly/terraform-provider-kops#594]
Running terraform apply after upgrading to v1.23.3 wants to update all instance groups removing the `kops.k8s.io/cluster` label every time.

```
 # module.k8s.kops_instance_group.nodes["c"] will be updated in-place
  ~ resource "kops_instance_group" "nodes" {
        id                           = "k8s.redacted/nodes-c"
      ~ labels                       = {
          - "kops.k8s.io/cluster" = "k8s.redacted" -> null
        }
        name                         = "nodes-c"
      ~ revision                     = 4 -> 5
        # (27 unchanged attributes hidden)
    }
```

**Comment by eddycharly** [comment]
Thanks for reporting, going to fix that quickly.

**Comment by eddycharly** [comment]
@argoyle I'm releasing `v1.23.4-alpha.1` with this fix, can you give it a try ?
If it's good I will release a stable version.

**Comment by argoyle** [comment]
Yes, will test as soon as the release is done

**Comment by argoyle** [comment]
<img width="479" alt="image" src="https://user-images.githubusercontent.com/328334/170241547-7dad9f7a-0aaf-4219-b255-f9cd4891b619.png">
💯

**Comment by eddycharly** [comment]
Great, I'll create `v1.23.4`.
Thanks for confirming !
