### ISSUE TITLE
How to trust Kubernetes api certificate

### ISSUE THREAD

**Issue by clayrisser** [eddycharly/terraform-provider-kops#640]
I'm able to generate a cluster, but when I run `curl https://kubernetes.default` from a pod, it fails with an error saying it doesn't trust the certificate.

How can I deploy kops so all the pods trust the Kubernetes api certificate?

**Comment by eddycharly** [comment]
The ca is self signed, curl will not automatically trust the ca.
Moreover, you need to authenticate and so on when calling the kube api, that’s why we have service accounts, tokens, etc…

**Comment by eddycharly** [comment]
Please provide more details on what you’re trying to do. Curl not trusting the cluster ca is completely normal.

**Comment by clayrisser** [comment]
@eddycharly I figured out that the reason it’s not working is because python does not trust intermediate certificates, and the ca that kops generates is an intermediate certificate. How do I prevent kops from creating intermediate certificates?

https://github.com/zalando/patroni/issues/1758

https://github.com/jupyterhub/kubespawner/issues/492

https://github.com/rook/rook/issues/3122#issuecomment-498320421

**Comment by eddycharly** [comment]
KOps creates self signed certs. I don’t remember if there’s an intermediate cert though. 

If there’s an intermediate cert, this is not the one to be used and it should be embedded in the ca cert.

**Comment by eddycharly** [comment]
The correct way to do it would be to use a k8s service account, that would bring all you need for talking with api server.

Not sure why it’s not used by percona.

**Comment by eddycharly** [comment]
Closing as this does not seem related to this provider, please reopen if needed.
