### ISSUE TITLE
[bug][1.24] aws-iam-authenticator config in cluster spec

### ISSUE THREAD

**Issue by mbolek** [eddycharly/terraform-provider-kops#718]
Hi, I think this might be a bug or just my misunderstanding.
I'm trying to use `aws-iam-authenticator` inside the `kops_cluster`. The [docs](https://registry.terraform.io/providers/eddycharly/kops/latest/docs/resources/cluster#aws_authentication_spec) suggest:
![image](https://user-images.githubusercontent.com/4385195/190609137-3ba4adff-cac3-4994-ba11-b1457c69ff92.png)
which I'd expect to look something like this:
```
  authentication {
    aws {
      backend_mode = "CRD,MountedFile"
      identity_mappings = [
        {
          arn = "arn:aws:iam::000000000000:user/Alice"
          username = "alice"
          groups = ["system:masters"]
        }
      ]
    }
  }
```
but this isn't accepted by TF:
```
│  101:       identity_mappings = [
│ 
│ An argument named "identity_mappings" is not expected here. Did you mean to
│ define a block of type "identity_mappings"?
```
I can update to the format which TF accepts/expects, but then I don't think it makes sense:
```
  authentication {
    aws {
      backend_mode = "CRD,MountedFile"
      identity_mappings {
        arn      = "arn:aws:iam::000000000000:user/Alice"
        username = "alice"
        groups   = ["system:masters"]
      }
    }
  }

```
because now it does:
```
      ~ authentication {
          ~ aws {
              + backend_mode = "CRD,MountedFile"

              + identity_mappings {
                  + arn      = "arn:aws:iam::000000000000:user/Alice"
                  + groups   = [
                      + "system:masters",
                    ]
                  + username = "alice"
                }
            }
        }
```
which allows creating only a single mapping.
Where do I go wrong?

Actually, I'll use the issue to ask two additional questions:
1. Is it possible to add any more info to terraform output? Think you've suggested in #529 to send logs to a file but this isn't always easily possible. I'm using atlantis to run all this and don't have an easy way to get to that log. 
2. Could you describe how does the `kops_cluster_updater` work? I mean, if I want to change k8s version, which naturally affects all the IGs, would the provider work in the same way as kOps by rolling them one after another, starting with masters? I'd imagine it works like this but without those extra logs it's a guess at the moment :)

Lastly, actually most importantly, thanks for taking the effort and creating the provider in the first place!

**Comment by eddycharly** [comment]
Thanks for reaching out @mbolek !
I'll look into it next week.

**Comment by eddycharly** [comment]
`identity_mappings` is a list, you should be able to have multiple instances, not just only one.
Does that solve your issue ?

**Comment by mbolek** [comment]
I'm afraid it doesn't. Unless I'm doing it completely wrong :) This case, `identity_mappings` as a list:
```
  authentication {
    aws {
      backend_mode = "CRD,MountedFile"
      identity_mappings = [
        {
          arn = "arn:aws:iam::000000000000:user/Alice"
          username = "alice"
          groups = ["system:masters"]
        }
      ]
    }
  }
```
doesn't work. Should it not be a list of maps?
When trying with an empty list:
```
  authentication {
    aws {
      identity_mappings = []
    }
  }
```
I still get an error when trying to plan:
```
│   on main.tf line 101, in resource "kops_cluster" "cluster":
│  101:       identity_mappings = []
│ 
│ An argument named "identity_mappings" is not expected here. Did you mean to
│ define a block of type "identity_mappings"?
```
Actually this seems to work, which is a bit confusing:
```
  authentication {
    aws {
      backend_mode = "CRD,MountedFile"
      identity_mappings {
        arn      = "arn:aws:iam::000000000000:user/Alice"
        username = "alice"
        groups   = ["system:masters"]
      }
      identity_mappings {
        arn      = "arn:aws:iam::000000000000:user/Bob"
        username = "bob"
        groups   = ["system:masters"]
      }
    }
  }
```
It properly updates cluster `config`:
```
  authentication:
    aws:
      backendMode: CRD,MountedFile
      identityMappings:
      - arn: arn:aws:iam::000000000000:user/Alice
        groups:
        - system:masters
        username: alice
      - arn: arn:aws:iam::000000000000:user/Bob
        groups:
        - system:masters
        username: bob
```

**Comment by eddycharly** [comment]
```hcl
  authentication {
    aws {
      backend_mode = "CRD,MountedFile"
      identity_mappings {
        arn      = "arn:aws:iam::000000000000:user/Alice"
        username = "alice"
        groups   = ["system:masters"]
      }
      identity_mappings {
        arn      = "arn:aws:iam::000000000000:user/Bob"
        username = "bob"
        groups   = ["system:masters"]
      }
    }
  }
```

This is the way we write lists in terraform.

**Comment by mbolek** [comment]
Right, think I got confused. [Docs](https://www.terraform.io/language/attr-as-blocks#defining-a-fixed-object-collection-value) suggest it as well :)
Thanks!
Would you mind commenting on those additional two questions from the first comment?

**Comment by eddycharly** [comment]
Sure.
1. There's nothing I can do for logs unfortunately, this is just not supported by terraform
2. This works exactly the same as `kOps` cli does, it will detect if a rollout is needed and will rollout all instance groups if necessary.

**Comment by mbolek** [comment]
Great, thanks!
