### ISSUE TITLE
Cannot upgrade provider version

### ISSUE THREAD

**Issue by lemaral** [eddycharly/terraform-provider-kops#763]
Trying to upgrade from 1.21.4 to any version upwards on darwinamd64, I get this
TF_LOG=DEBUG terrafom init -upgrade
[INFO]  Terraform version: 1.3.1
...
- Finding eddycharly/kops versions matching "1.21.4, 1.25.1"...
[DEBUG] GET https://registry.terraform.io/v1/providers/eddycharly/kops/versions
...
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider eddycharly/kops: no available releases match the given constraints 1.21.4, 1.25.1

It seems quite complicated to install a provider manually nowadays (used to be easier), so I wonder how can this can be fixed? I would not like to go back to the cli...

**Comment by eddycharly** [comment]
All versions are available from the [terraform registry](https://registry.terraform.io/providers/eddycharly/kops/latest/docs).

Not sure what the problem is, it should install automatically. I don't know why it doesn't want to install but it looks like an issue with your config.

**Comment by lemaral** [comment]
Thank you for the faster than light reply 👍 and sorry for the trouble.
I found the problem, an inconsistency between main version vs module version. I will open a usability issue on Terraform
